export let data = [
   // يوسف الخراز
   {
      name: "يوسف الخراز",
      id: "00",
      class: "4",
      tasmeaa: {
         "2024-6-23": {
            pages: [
               [521, 5, 6],
               [522, 5, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [[523, 4, 4]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [524, 4, 6],
               [525, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [[526, 4, 7]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [
               [527, 5, 7],
               [528, 4, 5],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [[529, 3, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [530, 2, 7],
               [531, 4, 8],
               [532, 1, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [[533, 3, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [
               [534, 4, 8],
               [535, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   //محمود حمام
   {
      name: "محمود حمام",
      id: "00",
      class: "5",
      tasmeaa: {
         "2024-6-23": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [[35, 4, 6]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [36, 4, 6],
               [37, 3, 6],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [38, 1, 3],
               [39, 3, 2],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [
               [40, 3, 5],
               [41, 4, 6],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [[42, 3, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [[43, 2, 7]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [44, 2, 5],
               [45, 4, 1],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [46, 3, 6],
               [47, 2, 5],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [
               [48, 2, 6],
               [49, 2, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // عبد المالك صيادي
   {
      name: "عبدالمالك صيادي",
      id: "01",
      class: "6",
      tasmeaa: {
         "2024-6-23": {
            pages: [],
            pointsOfQuite: 2,
            minutesLate: 90,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [33, 5, 8],
               [34, 4, 7],
               [35, 4, 4],
            ],
            pointsOfQuite: 4,
            minutesLate: 19,
            teacher: 2,
         },
         "2024-6-25": {
            pages: [
               [36, 2, 7],
               [37, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 13,
            teacher: 2,
         },
         "2024-6-26": {
            pages: [
               [38, 3, 7],
               [39, 4, 7],
               [40, 2, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 2,
         },
         "2024-6-27": {
            pages: [
               [41, 4, 7],
               [42, 3, 6],
               [43, 4, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 2,
         },
         "2024-6-30": {
            pages: [[44, 2, 7]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 2,
         },
         "2024-7-1": {
            pages: [
               [45, 5, 5],
               [46, 5, 4],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 2,
         },
         "2024-7-2": {
            pages: [
               [47, 5, 4],
               [48, 3, 7],
               [49, 5, 7],
               [50, 5, 4],
            ],
            pointsOfQuite: 4,
            minutesLate: 60,
            teacher: 2,
         },
         "2024-7-3": {
            pages: [
               [51, 4, 7],
               [52, 5, 7],
               [53, 4, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 2,
         },
         "2024-7-4": {
            pages: [[54, 2, 7]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 2,
         },
      },
   },
   // شهاب الشاطر
   {
      name: "شهاب الشاطر",
      id: "00",
      class: "6",
      tasmeaa: {
         "2024-6-23": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [56, 4, 6],
               [57, 5, 6],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [[58, 3, 6]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [59, 2, 7],
               [60, 2, 7],
               [61, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [[62, 1, 6]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [[63, 4, 8]],
            pointsOfQuite: 4,
            minutesLate: 12,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [[64, 4, 7]],
            pointsOfQuite: 4,
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [[65, 3, 6]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [[66, 3, 6]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [[67, 2, 6]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // عبد القادر النداف
   {
      name: "عبد القادر النداف",
      id: "00",
      class: "6",
      tasmeaa: {
         "2024-6-23": {
            pages: [[14, 3, 6]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [[15, 3, 7]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [[16, 5, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [[17, 2, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [
               [18, 3, 8],
               [19, 4, 4],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [[20, 2, 5]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [[21, 2, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [[22, 1, 7]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [[32, 5, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // جلال الدين دباغ
   {
      name: "جلال الدين دباغ",
      id: "00",
      class: "6",
      tasmeaa: {
         "2024-6-23": {
            pages: [
               [3, 4, 7],
               [4, 4, 7],
               [5, 4, 7],
               [6, 5, 8],
               [7, 5, 8],
               [8, 5, 8],
               [9, 5, 7],
               [10, 5, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [166, 3, 7],
               [11, 5, 8],
               [12, 4, 7],
               [13, 4, 8],
               [14, 2, 7],
               [15, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [[167, 5, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [[168, 3, 7]],
            pointsOfQuite: 4,
            minutesLate: 16,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [
               [169, 5, 8],
               [170, 4, 7],
               [171, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [[172, 5, 7]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [173, 2, 8],
               [174, 3, 7],
               [175, 4, 8],
               [176, 4, 8],
               [177, 4, 7],
               [178, 2, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 28,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [179, 5, 7],
               [180, 3, 7],
               [181, 4, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // عدنان البيطار
   {
      name: "عدنان البيطار",
      id: "00",
      class: "6",
      tasmeaa: {
         "2024-6-23": {
            pages: [
               [552, 5, 8],
               [553, 5, 8],
               [554, 5, 8],
               [555, 4, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [556, 5, 6],
               [557, 4, 6],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [558, 4, 6],
               [559, 3, 5],
               [560, 4, 8],
               [561, 4, 8],
               [562, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [563, 2, 8],
               [564, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [
               [565, 4, 7],
               [566, 5, 7],
               [567, 4, 8],
               [568, 4, 8],
               [569, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [[570, 4, 5]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [
               [571, 5, 8],
               [572, 3, 6],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [573, 4, 5],
               [574, 4, 8],
               [575, 4, 8],
               [576, 2, 6],
               [577, 4, 7],
               [578, 1, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [579, 3, 6],
               [580, 3, 7],
               [581, 5, 8],
               [582, 5, 5],
               [583, 2, 6],
               [584, 5, 8],
               [585, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [
               [586, 5, 8],
               [587, 5, 8],
               [588, 5, 8],
               [589, 5, 8],
               [590, 5, 8],
               [591, 5, 8],
               [592, 5, 8],
               [593, 5, 8],
               [594, 3, 8],
               [596, 5, 8],
               [597, 5, 8],
               [598, 3, 8],
               [599, 4, 8],
               [600, 5, 8],
               [601, 5, 8],
               [602, 5, 8],
               [603, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // عمرو التركماني
   {
      name: "عمرو التركماني",
      id: "00",
      class: "6",
      tasmeaa: {
         "2024-6-23": {
            pages: [
               [71, 4, 8],
               [72, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 20,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [73, 5, 8],
               [74, 4, 8],
               [75, 3, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [76, 4, 8],
               [77, 1, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 13,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [78, 3, 8],
               [79, 2, 8],
               [80, 1, 4],
            ],
            pointsOfQuite: 4,
            minutesLate: 35,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [[81, 3, 8]],
            pointsOfQuite: 4,
            minutesLate: 24,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 14,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [
               [82, 5, 8],
               [83, 5, 8],
               [84, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 18,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [85, 5, 8],
               [86, 4, 6],
               [87, 2, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [[88, 1, 8]],
            pointsOfQuite: 4,
            minutesLate: 17,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [
               [89, 5, 8],
               [90, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 39,
            teacher: 0,
         },
      },
   },
   // أحمد رجوب
   {
      name: "أحمد رجوب",
      id: "00",
      class: "6",
      tasmeaa: {
         "2024-6-23": {
            pages: [
               [27, 4, 6],
               [28, 5, 7],
               [29, 3, 8],
               [30, 4, 7],
               [31, 5, 4],
               [32, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [[33, 1, 8]],
            pointsOfQuite: 2,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [[34, 4, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [[35, 5, 4]],
            pointsOfQuite: 4,
            minutesLate: 13,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [36, 4, 6],
               [37, 4, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [[38, 4, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // جواد رمّو
   {
      name: "جواد رمّو",
      id: "00",
      class: "6",
      tasmeaa: {
         "2024-6-23": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [23, 3, 7],
               [24, 2, 6],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [[25, 5, 8]],
            pointsOfQuite: 4,
            minutesLate: 13,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [26, 3, 7],
               [27, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [
               [28, 3, 7],
               [29, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 14,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [[30, 5, 8]],
            pointsOfQuite: 4,
            minutesLate: 18,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 18,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [31, 5, 8],
               [32, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [
               [33, 5, 7],
               [34, 3, 5],
            ],
            pointsOfQuite: 4,
            minutesLate:16,
            teacher: 0,
         },
      },
   },
   // حازم الشامي
   {
      name: "حازم الشامي",
      id: "00",
      class: "6",
      tasmeaa: {
         "2024-6-23": {
            pages: [
               [14, 5, 6],
               [15, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [[16, 3, 7]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [17, 5, 8],
               [18, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [
               [19, 3, 5],
               [20, 2, 8],
               [21, 3, 5],
            ],
            pointsOfQuite: 0,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [[521, 5, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [[522, 4, 7]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [523, 4, 7],
               [524, 5, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [[525, 4, 6]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // يوسف صوفان
   {
      name: "يوسف صوفان",
      id: "00",
      class: "7",
      tasmeaa: {
         "2024-6-23": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 1000,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [2, 5, 8],
               [3, 5, 8],
               [4, 5, 8],
               [5, 5, 8],
               [6, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 13,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [7, 5, 8],
               [8, 5, 8],
               [9, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [
               [10, 2, 4],
               [11, 3, 3],
               [12, 4, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [
               [13, 3, 7],
               [14, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [15, 2, 8],
               [16, 2, 8],
               [17, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [[18, 5, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [
               [19, 2, 8],
               [20, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // حمزة النداف
   {
      name: "حمزة النداف",
      id: "00",
      class: "7",
      tasmeaa: {
         "2024-6-23": {
            pages: [
               // [50, 2, 8],
               // [51, 2, 8],
               // [52, 2, 8],
               // [53, 2, 8],
               // [54, 2, 8],
               // [55, 2, 8],
               // [56, 2, 8],
               // [57, 2, 8],
               // [58, 2, 8],
               // [59, 2, 8],
               // [60, 2, 8],
               // [61, 2, 8],
               // [62, 2, 8],
               // [63, 2, 8],
               // [64, 2, 8],
               // [65, 2, 8],
               [66, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [67, 3, 8],
               [68, 4, 8],
               [69, 5, 8],
               [70, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [71, 1, 8],
               [72, 5, 8],
               [73, 4, 8],
               [74, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [75, 3, 8],
               [76, 4, 8],
               [76, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [
               [78, 5, 8],
               [79, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [
               [80, 5, 8],
               [81, 5, 8],
               [82, 3, 8],
               [83, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [84, 5, 8],
               [85, 5, 6],
               [86, 5, 8],
               [87, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [[88, 5, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // عمر القصاب
   {
      name: "عمر القصاب",
      id: "00",
      class: "4",
      tasmeaa: {
         "2024-6-23": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [[48, 3, 7]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [[50, 5, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [[51, 2, 6]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [[52, 4, 4]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [[53, 1, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [54, 3, 8],
               [55, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [[56, 4, 6]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // محمد الحاج محمد
   {
      name: "محمد الحاج محمد",
      id: "00",
      class: "8",
      tasmeaa: {
         "2024-6-23": {
            pages: [
               [43, 3, 4],
               [44, 1, 4],
               [, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [45, 3, 7],
               [46, 3, 7],
               [47, 3, 6],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [[49, 3, 6]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [[50, 3, 5]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [
               [51, 4, 6],
               [52, 3, 5],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [[54, 2, 4]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // أيهم عبد المولى
   {
      name: "أيهم عبد المولى",
      id: "00",
      class: "8",
      tasmeaa: {
         "2024-6-23": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [103, 1, 5],
               [104, 2, 6],
               [105, 3, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [106, 1, 6],
               [107, 1, 6],
               [108, 2, 5],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [109, 3, 8],
               [110, 1, 7],
               [111, 2, 6],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [
               [112, 4, 3],
               [113, 2, 3],
               [114, 3, 7],
               [115, 5, 5],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [116, 1, 1],
               [117, 3, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [118, 5, 4],
               [119, 4, 6],
               [120, 5, 5],
               [121, 2, 5],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [
               [122, 5, 4],
               [123, 4, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // يامن المحمد
   {
      name: "يامن المحمد",
      id: "00",
      class: "8",
      tasmeaa: {
         "2024-6-23": {
            pages: [
               [190, 4, 6],
               [191, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [192, 4, 7],
               [193, 2, 8],
               [194, 4, 6],
               [195, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [196, 2, 7],
               [197, 5, 8],
               [198, 5, 8],
               [199, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [200, 3, 8],
               [201, 3, 8],
               [202, 4, 7],
               [203, 3, 8],
               [204, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [
               [205, 4, 5],
               [206, 4, 6],
               [207, 2, 7],
               [208, 2, 6],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [
               [209, 3, 7],
               [210, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [
               [211, 1, 6],
               [212, 2, 7],
               [213, 5, 7],
               [214, 3, 6],
               [215, 2, 4],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [216, 5, 8],
               [217, 2, 5],
               [218, 3, 5],
               [219, 3, 6],
               [220, 3, 7],
               [221, 2, 5],
            ],
            pointsOfQuite: 2,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [
               [222, 4, 8],
               [223, 4, 7],
               [224, 2, 7],
               [225, 3, 8],
               [226, 4, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // عبد العزيز شلب الشام
   {
      name: "عبد العزيز شلب الشام",
      id: "00",
      class: "8",
      tasmeaa: {
         "2024-6-23": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [111, 2, 8],
               [112, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [113, 5, 8],
               [114, 1, 6],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [[115, 3, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 42,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [[116, 4, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [
               [117, 1, 7],
               [118, 2, 7],
               [, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [119, 2, 7],
               [120, 1, 5],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [121, 2, 7],
               [122, 3, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // نور الدين التلاوي
   {
      name: "نور الدين التلاوي",
      id: "00",
      class: "8",
      tasmeaa: {
         "2024-6-23": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 16,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [113, 4, 4],
               [113, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [[115, 5, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [116, 3, 8],
               [117, 1, 1],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [[118, 1, 7]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [
               [119, 5, 5],
               [120, 4, 5],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [
               [121, 5, 7],
               [122, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [123, 2, 7],
               [124, 1, 5],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [125, 2, 5],
               [126, 5, 7],
               [127, 3, 6],
               [128, 1, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 63,
            teacher: 0,
         },
      },
   },
   // مرسل الشبعان
   {
      name: "مرسل الشبعان",
      id: "00",
      class: "8",
      tasmeaa: {
         "2024-6-23": {
            pages: [[24, 3, 0]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [25, 1, 6],
               [26, 2, 4],
            ],
            pointsOfQuite: 4,
            minutesLate: 52,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [27, 2, 8],
               [28, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [29, 3, 6],
               [30, 4, 5],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [[31, 1, 6]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [[32, 2, 7]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [33, 2, 7],
               [34, 5, 8],
               [35, 2, 5],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [36, 4, 6],
               [37, 3, 8],
               [38, 4, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [
               [39, 3, 8],
               [40, 3, 4],
               [41, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // فرحان القصاب
   {
      name: "فرحان القصاب",
      id: "00",
      class: "8",
      tasmeaa: {
         "2024-6-23": {
            pages: [[125, 2, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [126, 3, 7],
               [127, 5, 8],
               [128, 2, 8],
               [129, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [130, 1, 7],
               [131, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [132, 4, 6],
               [133, 2, 5],
               [134, 2, 6],
               [135, 2, 7],
               [136, 5, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [
               [137, 4, 7],
               [138, 2, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [[139, 5, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [
               [140, 3, 3],
               [141, 3, 3],
               [142, 1, 6],
               [143, 2, 5],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [144, 2, 8],
               [145, 3, 8],
               [146, 3, 8],
               [147, 4, 8],
               [148, 4, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [149, 2, 7],
               [150, 5, 8],
               [151, 4, 8],
               [152, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [
               [153, 2, 7],
               [154, 4, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // يحيى صوفان
   {
      name: "يحيى صوفان",
      id: "00",
      class: "9",
      tasmeaa: {
         "2024-6-23": {
            pages: [
               [195, 4, 8],
               [196, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 24,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [197, 5, 7],
               [198, 4, 7],
               [199, 3, 6],
               [200, 5, 8],
               [201, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [202, 3, 8],
               [203, 2, 8],
               [204, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [
               [205, 2, 8],
               [206, 2, 8],
               [207, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [
               [208, 5, 8],
               [209, 3, 8],
               [210, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [[211, 4, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [212, 3, 6],
               [213, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [
               [214, 5, 8],
               [215, 5, 8],
               [216, 1, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // تامر النداف
   {
      name: "تامر النداف",
      id: "00",
      class: "10",
      tasmeaa: {
         "2024-6-23": {
            pages: [
               [3, 5, 8],
               [4, 5, 8],
               [5, 5, 8],
               [6, 5, 8],
               [7, 5, 8],
               [8, 5, 8],
               [9, 4, 7],
               [10, 4, 7],
               [11, 4, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [12, 5, 7],
               [13, 5, 7],
               [14, 5, 8],
               [15, 3, 8],
               [16, 3, 8],
               [17, 3, 8],
               [18, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [20, 4, 8],
               [21, 4, 8],
               [22, 4, 8],
               [23, 5, 7],
               [24, 5, 8],
               [25, 5, 8],
               [26, 4, 8],
               [27, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [28, 5, 8],
               [29, 5, 8],
               [30, 4, 8],
               [31, 4, 8],
               [32, 3, 8],
               [33, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [
               [34, 3, 8],
               [35, 4, 8],
               [36, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [[37, 5, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [38, 5, 8],
               [39, 4, 8],
               [40, 4, 8],
               [41, 5, 8],
               [42, 5, 8],
               [43, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [[44, 5, 8]],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
      },
   },
   // فادي التلاوي
   {
      name: "فادي التلاوي",
      id: "00",
      class: "11",
      tasmeaa: {
         "2024-6-23": {
            pages: [
               [126, 5, 8],
               [127, 5, 8],
               [128, 4, 8],
               [129, 4, 8],
               [130, 4, 8],
               [131, 4, 8],
               [132, 4, 8],
               [133, 5, 8],
               [134, 5, 8],
               [135, 5, 8],
               [136, 5, 8],
               [137, 5, 8],
               [138, 5, 8],
               [139, 5, 8],
               [140, 3, 8],
               [141, 3, 8],
               [142, 3, 8],
               [143, 3, 8],
               [144, 3, 8],
               [145, 3, 8],
               [146, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 35,
            teacher: 0,
         },
         "2024-6-24": {
            pages: [
               [147, 4, 8],
               [148, 5, 8],
               [149, 5, 8],
               [150, 4, 7],
               [151, 5, 8],
               [152, 5, 7],
               [153, 5, 4],
               [154, 2, 4],
               [155, 4, 5],
               [156, 5, 8],
               [157, 4, 8],
               [158, 4, 8],
               [159, 5, 4],
               [160, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-25": {
            pages: [
               [161, 4, 8],
               [162, 4, 8],
               [163, 4, 8],
               [164, 4, 8],
               [165, 4, 8],
               [166, 4, 8],
               [167, 4, 8],
               [168, 4, 8],
               [169, 4, 8],
               [170, 4, 8],
               [171, 4, 8],
               [172, 3, 8],
               [173, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-26": {
            pages: [
               [174, 4, 7],
               [175, 4, 7],
               [176, 4, 7],
               [177, 4, 7],
               [178, 4, 7],
               [179, 4, 7],
               [180, 4, 7],
               [181, 4, 7],
               [182, 4, 7],
               [183, 4, 7],
               [184, 4, 7],
               [185, 4, 7],
               [186, 4, 8],
               [187, 4, 8],
               [188, 4, 8],
               [189, 4, 8],
               [190, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-6-27": {
            pages: [
               [191, 5, 8],
               [192, 1, 8],
               [193, 4, 8],
               [194, 5, 8],
               [195, 5, 7],
               [196, 5, 8],
               [197, 1, 7],
               [198, 5, 8],
               [199, 3, 7],
               [200, 5, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 14,
            teacher: 0,
         },
         "2024-6-30": {
            pages: [
               [201, 3, 8],
               [202, 5, 7],
               [203, 3, 3],
               [204, 3, 8],
               [205, 3, 8],
               [206, 2, 8],
               [207, 4, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-1": {
            pages: [
               [209, 3, 7],
               [210, 3, 7],
               [211, 3, 7],
               [212, 3, 7],
               [213, 3, 7],
               [214, 3, 7],
               [215, 3, 7],
               [216, 3, 6],
               [217, 3, 6],
               [218, 3, 6],
               [219, 3, 6],
               [220, 3, 6],
               [221, 4, 6],
               [222, 4, 6],
               [223, 4, 6],
               [224, 4, 6],
               [225, 4, 6],
               [226, 4, 6],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-2": {
            pages: [
               [227, 4, 8],
               [228, 2, 8],
               [229, 5, 8],
               [230, 5, 8],
               [231, 4, 8],
               [232, 4, 8],
               [233, 2, 8],
               [234, 5, 8],
               [235, 4, 8],
               [236, 5, 8],
               [237, 4, 8],
               [238, 5, 8],
               [239, 5, 8],
               [240, 3, 8],
               [241, 4, 7],
               [242, 5, 8],
               [243, 2, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 14,
            teacher: 0,
         },
         "2024-7-3": {
            pages: [
               [244, 3, 8],
               [245, 3, 8],
               [246, 3, 8],
               [247, 3, 8],
               [248, 3, 8],
               [249, 3, 8],
               [250, 4, 8],
               [251, 4, 7],
               [252, 4, 7],
               [253, 4, 7],
            ],
            pointsOfQuite: 4,
            minutesLate: 0,
            teacher: 0,
         },
         "2024-7-4": {
            pages: [
               [254, 4, 8],
               [255, 4, 8],
               [256, 4, 8],
               [257, 3, 8],
               [258, 3, 8],
            ],
            pointsOfQuite: 4,
            minutesLate: 73,
            teacher: 0,
         },
      },
   },
];
let c = {
   name: "name",
   id: "00",
   class: "0",
   tasmeaa: {
      "2024-6-23": {
         pages: [
            [, 5, 8],
            [, 5, 8],
            [, 5, 8],
         ],
         pointsOfQuite: 4,
         minutesLate: 0,
         teacher: 0,
      },
      "2024-6-24": {
         pages: [
            [, 5, 8],
            [, 5, 8],
            [, 5, 8],
         ],
         pointsOfQuite: 4,
         minutesLate: 0,
         teacher: 0,
      },
      "2024-6-25": {
         pages: [
            [, 5, 8],
            [, 5, 8],
            [, 5, 8],
         ],
         pointsOfQuite: 4,
         minutesLate: 0,
         teacher: 0,
      },
      "2024-6-26": {
         pages: [
            [, 5, 8],
            [, 5, 8],
            [, 5, 8],
         ],
         pointsOfQuite: 4,
         minutesLate: 0,
         teacher: 0,
      },
      "2024-6-27": {
         pages: [
            [, 5, 8],
            [, 5, 8],
            [, 5, 8],
         ],
         pointsOfQuite: 4,
         minutesLate: 0,
         teacher: 0,
      },
      "2024-6-30": {
         pages: [
            [, 5, 8],
            [, 5, 8],
            [, 5, 8],
         ],
         pointsOfQuite: 4,
         minutesLate: 0,
         teacher: 0,
      },
      "2024-7-1": {
         pages: [
            [, 5, 8],
            [, 5, 8],
            [, 5, 8],
         ],
         pointsOfQuite: 4,
         minutesLate: 0,
         teacher: 0,
      },
      "2024-7-2": {
         pages: [
            [, 5, 8],
            [, 5, 8],
            [, 5, 8],
         ],
         pointsOfQuite: 4,
         minutesLate: 0,
         teacher: 0,
      },
      "2024-7-3": {
         pages: [
            [, 5, 8],
            [, 5, 8],
            [, 5, 8],
         ],
         pointsOfQuite: 4,
         minutesLate: 0,
         teacher: 0,
      },
      "2024-7-4": {
         pages: [
            [, 5, 8],
            [, 5, 8],
            [, 5, 8],
         ],
         pointsOfQuite: 4,
         minutesLate: 0,
         teacher: 0,
      },
   },
};
